### PR TITLE
Update repo URLs

### PR DESCRIPTION
**Pull request by tamuri**
For move of LMSgrowth2 from UCL to statist7. Once Travis has been set up for this repo, we can update the build status icon URLs (at top of README)

### CODE REVIEW

**Comment by tamuri** [comment]
Please don't merge yet, Travis didn't pick this up.

**Comment by tamuri** [comment]
Hi Tim - can you please visit [https://travis-ci.com/github/statist7/LMSgrowth2](https://travis-ci.com/github/statist7/LMSgrowth2) and see whether Travis can see this repo.

**Comment by statist7** [comment]
It can see the repo , but the most recent PR is #45 which was after I'd transferred the repo to me but before I signed up to Travis. Should I restart the build?

**Comment by tamuri** [comment]
Can you try going to your [profile page](https://travis-ci.com/account/repositories) on Travis and then clicking the 'Sync account' button to see if that helps.

**Comment by statist7** [comment]
I did that, and it said, last synced 7 hours ago.

**Comment by statist7** [comment]
Can we switch Travis off, run the PR to update the URL, and then switch it on again?

**Comment by tamuri** [comment]
No, something non-obvious going on. Let's wait and see if it refreshes itself. I'll speak to Mose (our resident expert on CI) on Monday.

**Pull request closed without merging**
